In [1]:
import numpy as np
import random as rm
import pandas as pd
from random import seed
from random import random
import matplotlib.pyplot as plt
from pylab import *
from scipy.optimize import curve_fit
from scipy.stats import bernoulli, binom, norm
from scipy import integrate

In [27]:
mu_list = [0,17.5]        # mean list of target distribution
sigma_list = [.5,1]       # variance list of target distribtuion
alpha_list = [0.4,0.6]    # constant list of target distribution
p = 0.75                  # the rate coefficient between target distribution and proposed distribution
n = 10                  # number of simulations
y0 =15                    # initial position of y
x0 = 10                   # initial position of x
sigma = 10                # 
epsilon = 0.05            #

In [2]:
def f_pi(x,mu_list,alpha_list,sigma_list):
    val = 0
    for i in range(len(mu_list)):
        val += alpha_list[i]*norm.pdf(x,mu_list[i], sigma_list[i]**0.5)
    return val

In [12]:
def pdf_eta(x,mu_list,alpha_list,sigma_list):
        return f_pi(x,mu_list,alpha_list,sigma_list)**p

In [13]:
print(f_pi(1,mu_list,alpha_list,sigma_list))
print(f_pi(2,mu_list,alpha_list,sigma_list))
print(f_pi(3,mu_list,alpha_list,sigma_list))
print(pdf_eta(1,mu_list,alpha_list,sigma_list))

0.08302149948411897
0.004133397070818414
2.7850610389349622e-05
0.15466531478148507


In [19]:
for i in range(0,5):
    ab = []
    ab.append(1)
print(ab)

[1]


In [46]:
a = [[3,4]]
b = np.append(a,[[1,2]],axis=0)
c = np.append(b,[2,3])
d = np.append([[1,2,3],[4,5,6]],[[7,8,9]],axis=0)
print(b)

[[3 4]
 [1 2]]


In [83]:
arr = np.empty((0,4), int)
print("Empty array:")
print(arr)
arr1 = np.append(arr, np.array([[10,20,30,70]]), axis=0)
arr2 = np.append(arr, np.array([[40,50,60,80]]), axis=0)
print("After adding two new arrays:")
print(arr2)

Empty array:
[]
After adding two new arrays:
[[40 50 60 80]]


In [25]:
def simulate(mu_list, sigma_list, alpha_list, n, p, x0, y0, sigma, epsilon):
    def f_pi(x):
        val = 0
        for i in range(len(mu_list)):
            val += alpha_list[i]*norm.pdf(x,mu_list[i], sigma_list[i]**0.5)
        return val
    # y value on point x of the f_pi(x) curve
    
    def pdf_eta(x):
        return f_pi(x)**p
    # y value on point x of the pdf_eta(x) curve

    c = integrate.quad(pdf_eta, -np.inf, np.inf)[0]
    
    def f_eta(x):
        return pdf_eta(x)/c
    
    def g(x):
        return(f_pi(x)/f_eta(x))
    
    def p_kernel(y0, sigma, n):
        count = 0
        Yn = y0
        estimator = [y0]
        while count<n:
            y = np.random.normal(Yn, sigma)
            u = np.random.uniform(0,1)
            alpha = min((pdf_eta(y)/pdf_eta(Yn)),1)
            if u <= alpha:
                estimator.append(y)
                Yn = y
                count +=1
                print(Yn)
        return estimator
    
    est = p_kernel(y0, sigma, n)
    return est
    
    def k_kernel(x0, sigma): ##
        count = 0
        Xn = x0
        estimator = [x0]
        while count<1:
            y = np.random.normal(Xn,sigma)
            u = np.random.uniform(0,1)
            alpha = min((pdf_eta(y)/pdf_eta(Xn)),1)
            if u <= alpha:
                estimator.append(y)
                Xn = y
                count +=1
        return estimator[-1]
    
    #esti = k_kernel(x0, sigma)
    #return esti
    
    def bernoulli_list(epsilon, n):
        b_list = bernoulli(epsilon).rvs(n)
        return b_list
    
    #a = bernoulli_list(0.2, 10)
    #return a

In [29]:
print(simulate(mu_list, sigma_list, alpha_list, 2, p, x0, y0, sigma, epsilon))

17.35657941034068
18.34799203896287
[15, 17.35657941034068, 18.34799203896287]


In [126]:
x0 = [1,2,3]
y0 = [4,5,6]
a = np.array([x0,y0])
b = a[1][:4]
print(b.ndim)

for i in range(1,3):
    print(1)
    
c = np.array([1,2])
print(c)

1
1
1
[1 2]


In [179]:
new_matrix = np.empty((0,1), int)
new_matrix = np.append(new_matrix, [[1]], axis = 0)
new_matrix = np.append(new_matrix, [[2]], axis = 0)
print(new_matrix)
a = np.array([[1],[2],[3],[4]])
print(a[1])
print(new_matrix[0])
print(type(new_matrix[0][0]))
print(type(a[0][0]))
c = list(new_matrix[1])
c.append(3)
print(c[1])
new_matrix = np.append(new_matrix,[[c[1]]],axis=0)
new_matrix[0] = [c[0]]
print(new_matrix)


[[1]
 [2]]
[2]
[1]
<class 'numpy.int64'>
<class 'numpy.int64'>
3
[[2]
 [2]
 [3]]


In [202]:
def simulate(mu_list, sigma_list, alpha_list, n, p, x0, y0, sigma, epsilon):
    def f_pi(x):
        val = 0
        for i in range(len(mu_list)):
            val += alpha_list[i]*norm.pdf(x,mu_list[i], sigma_list[i]**0.5)
        return val
    # y value on point x of the f_pi(x) curve
    
    def pdf_eta(x):
        return f_pi(x)**p
    # y value on point x of the pdf_eta(x) curve

    c = integrate.quad(pdf_eta, -np.inf, np.inf)[0]
    
    def f_eta(x):
        return pdf_eta(x)/c
    
    def g(x):
        return(f_pi(x)/f_eta(x))
    
    def p_kernel(y0, sigma, n):
        count = 0
        Yn = y0
        estimator = [y0]
        while count<n:
            y = np.random.normal(Yn, sigma)
            u = np.random.uniform(0,1)
            alpha = min((pdf_eta(y)/pdf_eta(Yn)),1)
            if u <= alpha:
                estimator.append(y)
                Yn = y
                count +=1
        return estimator

    def k_kernel(x0, sigma):
        count = 0
        Xn = x0
        estimator = [x0]
        while count<1:
            y = np.random.normal(Xn,sigma)
            u = np.random.uniform(0,1)
            alpha = min((pdf_eta(y)/pdf_eta(Xn)),1)
            if u <= alpha:
                estimator.append(y)
                Xn = y
                count +=1
        return estimator[-1]
    
    def sum_g(sum_old, yn):
        sum_new = sum_old + g(yn)
        return sum_new

    def prob_list(y, sum_new):
        prob_list = []
        for i in y:
            prob_list.append(g(i)/sum_new)
        return prob_list
    
    def bernoulli_list(epsilon, n):
        b_list = bernoulli(epsilon).rvs(n)
        return b_list
    
    def x_sample(x0, epsilon, y0, n, sigma):
        X_list = [x0]
        Y_list = [y0]
        sum_gs = g(y0)
        Y_list = p_kernel(y0,sigma,n)
        for k in range(1, n):
            sum_gs = sum_g(sum_gs, Y_list[k])
            prob_list_Ys = prob_list(Y_list[:k+1], sum_gs)
            bernoullis = bernoulli_list(epsilon, 1)
            i = bernoullis
            if i == 0:
                X_list.append(k_kernel(x0, sigma))
            if i == 1:
                X_list.append(np.random.choice(Y_list[:k+1], p = prob_list_Ys))
            x0 = X_list[-1]
        return X_list
    
    x_new = x_sample(x0, epsilon, y0, n, sigma)
    return x_new

In [204]:
n=5
print(simulate(mu_list, sigma_list, alpha_list, n, p, x0, y0, sigma, epsilon))

[10, 11.113847088925505, -0.5730285250239984, -1.1999787410105833, 17.750814014362383]


In [198]:
x  = np.empty((0,2), int)
x= np.append(x,[[1,2]],axis=0)
print(x)

a=[1,3]
b = [2,3,4]
a[1] = b[-1]
print(a)

for i in range(1,5):
    print (i)

[[1 2]]
[1, 4]
1
2
3
4


In [217]:
a = np.matrix([[1,2],[3,4]])
print(a.sum())

x = np.matrix([[1, 2], [4, 3]])
print(x.size)


10
4


In [3]:
a= np.array([1])
print(type(a[0]))

<class 'numpy.int64'>


In [58]:
prob_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(prob_matrix.flatten())



[1 2 3 4 5 6 7 8 9]


In [55]:
for i in range(5):
    print(i)

0
1
2
3
4
